### ISSUE TITLE
Openfold

### ISSUE THREAD

**Issue by srchamberlain** [ubccr/software-layer#396]
Our group is looking to install Openfold version 2.1 for our group, and I am looking for some help on adjusting the easybuild recipe. I have already found an old easybuild recipe for Openfold version 1.0 in your easybuild recipe lists, and I have copied that recipe but updated it for version 2.1, with all dependencies updated to those listed on ccr. (Current recipe file can be found at /projects/academic/tdgrant/easybuild/OpenFold-2.1.0-foss-2021b-CUDA-11.8.0.eb). 

I have already ensured I have the proper dependencies installed for our group that were not available on the ccr previously (again, used existing easybuild recipe, they were rather straight-forward). The issue I get to arises with the sanity check of the software (see error below). The 'absl' module is a sub-module of tensorflow, which requires gcc. The old easybuild recipe (as seen in the name) uses foss-2021b, but I presume I also need gcc 11.2.0. Is this as straightforward as adding a second toolchain to the easybuild file, and tensorflow as a dependency? Please advise. 

output for command: python -c "import ml_collections"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/projects/academic/tdgrant/easybuild/2023.01/software/avx512/MPI/gcc/11.2.0/openmpi/4.1.1/openfold/2.1.0-CUDA-11.8.0/lib/python3.9/site-packages/ml_collections/__init__.py", line 18, in <module>
    from ml_collections.config_dict import ConfigDict
  File "/projects/academic/tdgrant/easybuild/2023.01/software/avx512/MPI/gcc/11.2.0/openmpi/4.1.1/openfold/2.1.0-CUDA-11.8.0/lib/python3.9/site-packages/ml_collections/config_dict/__init__.py", line 18, in <module>
    from .config_dict import _Op
  File "/projects/academic/tdgrant/easybuild/2023.01/software/avx512/MPI/gcc/11.2.0/openmpi/4.1.1/openfold/2.1.0-CUDA-11.8.0/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 33, in <module>
    from absl import logging
ModuleNotFoundError: No module named 'absl'

**Comment by dsajdak** [comment]
@srchamberlain If you want us to attempt the install, we can do that.  If you'd like to do it yourself, please submit a ticket to CCR Help and we'll help you through the issues you're having there, rather in a GitHub issue.  Thanks!

**Comment by srchamberlain** [comment]
We will want to eventually do this for ourselves, so I have submitted a ticket through CCR Help, thank you.
